version: "3.8"
services:
  todo-app:
    container_name: todo-app
    image: htrvolker/todo-app:1.21
    ports:
    - target: 5000
      published: 80
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
    deploy:
      replicas: 10
  
