pipeline{
    agent any
    environment{
        YOUR_NAME="harry"
    }
    stages{
        stage("Configure Swarm"){
            steps{
                sh "cd ansible && /home/jenkins/.local/bin/ansible-playbook -i inventory playbook.yaml"
            }
        }
        stage("Deploy application"){
            steps{
                sh "bash jenkins/deploy_stack.sh"
            }
        }
    }
}