---
- name: initialize docker swarm
  become: true
  hosts: master
  roles:
    - docker
    - docker-swarm-init
- name: add workers to swarm
  become: true
  hosts: workers
  roles:
    - docker
    - docker-swarm-workers
